name: Windows RDP

on: [push, pull_request]

jobs:
  rdp:
    runs-on: windows-latest

    steps:
    - name: Set up RDP
      run: |
        powershell -Command "Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0"
        powershell -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
      
    - name: Create RDP User
      run: |
        net user github /add
        net localgroup administrators github /add
        powershell -Command "Set-LocalUser -Name 'github' -Password (ConvertTo-SecureString -AsPlainText 'YourPasswordHere' -Force)"
        
    - name: Display RDP Connection Info
      run: |
        $ip = (Invoke-RestMethod -Uri 'http://ipinfo.io/json').ip
        echo "RDP server is running. Connect to $ip with username 'github' and your specified password."
