name: Run Docker Container

on: 
  push:
    branches:
      - main

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ydiskyha }}
        password: ${{ secrets.12345678qwertyuiPO{ }}

    - name: Run Docker Container
      run: docker run -p 6070:80 dorowu/ubuntu-desktop-lxde-vnc
