name: Install Panel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Sesuaikan dengan versi Python yang Anda butuhkan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install panel  # Perintah untuk menginstal Panel

    - name: Verify installation
      run: |
        panel --version  # Periksa versi Panel yang terinstal
